### ISSUE TITLE
Link button

### ISSUE THREAD

**Issue by marianperca** [jhollingworth/bootstrap-wysihtml5#110]
Hi! I noticed that when you click on the "Link" button, at the bottom of the modal appears 'body'.
I think line 346:

``` javascript
insertLinkModal.append('body').modal('show');
```

should be changed to 

``` javascript
insertLinkModal.modal('show');
```

**Comment by anu-vaid** [comment]
I am having the same issue
![Screen Shot 2013-02-08 at 12 13 01 PM](https://f.cloud.github.com/assets/1835045/140728/f95d7386-722b-11e2-9769-ed316ea5aa83.png)
