### ISSUE TITLE
Auto resize

### ISSUE THREAD

**Issue by lucasvalhos** [jhollingworth/bootstrap-wysihtml5#113]
It would be interesting to an auto resize the textarea.

**Comment by kb6673** [comment]
@lucascarvalho I tried combining this with jQuery AutoGrow to no avail. Did you manage to solve this?

**Comment by edslocomb** [comment]
https://github.com/xing/wysihtml5/issues/18

Autoresize is marked for inclusion in 0.4.0 of the upstream source, so it might percolate up from there eventually.  In the meantime, there are ways you can add autoresize manually, discussion of which can be found in the issue referenced above.

**Comment by lucasvalhos** [comment]
thanks
