### ISSUE TITLE
Multiple wysiwyg on the same page issue

### ISSUE THREAD

**Issue by romain-bourgois** [jhollingworth/bootstrap-wysihtml5#115]
When you try to put 3 wysiwyg on textareas on the same page, there is a DOM issue : 
Uncaught Error: HIERARCHY_REQUEST_ERR: DOM Exception 3
There is no issues with the 0.3.0 version, the error appeared in 0.3.1

**Comment by edslocomb** [comment]
Where did you download version 0.3.1?

wysihtml5 is currently at version 0.3.0, and bootstrap-wysihtml is at version 0.0.2

**Comment by romain-bourgois** [comment]
Sorry about that, my mistake... The issue comes from this gem: https://github.com/Nerian/bootstrap-wysihtml5-rails, not yours.
