### ISSUE TITLE
consider changing the numeric list icon

### ISSUE THREAD

**Issue by troygoode** [jhollingworth/bootstrap-wysihtml5#12]
Figuring out which button represents bullets vs numbers isn't very intuitive with the current icons.

![http://i.imgur.com/dmWKP.png](http://i.imgur.com/dmWKP.png)

**Comment by buzzedword** [comment]
Looks like this is coming from bootstrap's provided "glyphicons-halflings" icon set. Doesn't appear to have a numeric list icon anywhere in it. That's unfortunate. Not going to stomp on @jhollingworth's design here, nothing I can patch for ya.

**Comment by jhollingworth** [comment]
@buzzedword  thanks for looking - looks like I shall have to dust off my photoshop skills!
