### ISSUE TITLE
Multiple instances per page

### ISSUE THREAD

**Issue by kb6673** [jhollingworth/bootstrap-wysihtml5#121]
I can't seem to add multiple instances per page

_Works_

```
$(function() {
    $("#MedicNotes").wysihtml5();
});
```

_Doesn't work_

```
$(function() {
    $("#MedicNotes").wysihtml5();

    $("#MedicAdminNotes").wysihtml5();
});
```

**Comment by edslocomb** [comment]
Are you using a recent download?  There was a bug with multiple editors per page that was fixed not too long ago.

If that doesn't do it for you, could you be a little more specific about "doesn't work"?  Do any editors appear on the page?  Are they fully functional?  Does your browser report any js errors?  etc...

**Comment by kb6673** [comment]
My bad. I'll use the latest version!
