### ISSUE TITLE
License is incompatible with wysihtml5

### ISSUE THREAD

**Issue by karlbohlmark** [jhollingworth/bootstrap-wysihtml5#13]
It's not possible to license this code under Apache license if it uses wysihtml5 which is GPL licensed. http://www.apache.org/licenses/GPL-compatibility.html

**Comment by jhollingworth** [comment]
Bugger. Have you any suggestions of any compatible licences which aren't GPL? I hate GPL. There's an issue raised on the wysihtml5 project to change the licence https://github.com/xing/wysihtml5/issues/22

**Comment by karlbohlmark** [comment]
Well, you're pretty much screwed until hopefully xing decides to change the license of wysihtml5. (Which seems not entirely unlikely, it's not really their core business to write wysiwyg editors)

**Comment by buzzedword** [comment]
Being addressed at xing/wysihtml5#22 -- you're borked until that's fixed :(

**Comment by troygoode** [comment]
Yeah, just change it to GPL for now and mirror whatever xing does. If xing changes it to MIT or Apache (or whatever) you should change with him at that point - for now you really have no choice but to switch to GPL...

**Comment by jhollingworth** [comment]
Updated it (https://github.com/jhollingworth/bootstrap-wysihtml5/commit/e4c99a28e73ec95538faf00cd492577596b3d044). That's put a dampener on my day :(

**Comment by buzzedword** [comment]
This should put a lighter step in your day-- wysihtml5 has been updated to the MIT license. https://github.com/xing/wysihtml5/issues/22#issuecomment-4612193
