### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by deanpcmad** [jhollingworth/bootstrap-wysihtml5#15]
Does Bootstrap wysiwyg editor support Markdown at all? As in saving as markdown?

**Comment by jhollingworth** [comment]
Sorry, HTML only unfortunately. I think this project is probably what you are looking for https://github.com/samwillis/pagedown-bootstrap :)

**Comment by deanpcmad** [comment]
Oh cool, thanks :)

**Comment by buzzedword** [comment]
That project has a pretty neat ordered list icon (ref #12) in case you're interested.
