### ISSUE TITLE
Not wrapping correct HTML

### ISSUE THREAD

**Issue by sirvine** [jhollingworth/bootstrap-wysihtml5#16]
I've got bootstrap-wysihtml5 (using wysihtml5 v0.3.0_rc1) implemented in a Rails 3.2.2 app.  

The form loads without any issue – no errors in the browser console, just the "heya" message from wysihtml5.js.  The text area in my form appears as it should, with the dropdown and button groups for styling text.  The iframe appears correctly in the page source, and I can style text within the text area.

However, when I submit the form, I'm getting the wrong HTML on the server side.  Specifically, only `<br>` tags are posted, and any other tags are appearing as `<span>`.

For example, an ordered list that appears fine in the text area arrives at the server as follows:

```
<span><span>One<br></span><span>Two<br></span><span>Three<br></span></span>
```

I'm not sure if this is Rails sanitizing the input, or wysihtml5 wrapping it incorrectly.  Any ideas?

**Comment by mik356ua** [comment]
I think they forgot to add "parserRules" option. Without this option original Wysihtml5 script won't save any tags except `<br>` and `<span>`

**Comment by sirvine** [comment]
Yes, I think you are correct.  I tried this, but it doesn't fix the issue:

```
var wysihtml5ParserRules = {
    tags: {
      strong: {},
      b:      {},
      i:      {},
      em:     {},
      br:     {},
      p:      {},
      div:    {},
      span:   {},
      ul:     {},
      ol:     {},
      li:     {},
      a:      {
        set_attributes: {
          target: "_blank",
          rel:    "nofollow"
        },
        check_attributes: {
          href:   "url" // important to avoid XSS
        }
      }
    }
  };

  $('.wysihtml5').wysihtml5({ "parserRules" : wysihtml5ParserRules });
```

**Comment by mik356ua** [comment]
To make it work you should also make some modifications to bootstrap-wysihtml5.js. I changed it this way:

```
39 - toolbar: this.toolbar.attr('id')
39 + toolbar: this.toolbar.attr('id'),
40 + parserRules: options ? options.parserRules : null
```

**Comment by sirvine** [comment]
I see.  Works like a charm.  Thanks!

**Comment by hinrik** [comment]
For the record, I believe I have a fitting patch for this in https://github.com/jhollingworth/bootstrap-wysihtml5/pull/20

**Comment by jhollingworth** [comment]
[@hinrik's change](https://github.com/jhollingworth/bootstrap-wysihtml5/commit/d9c43dedf7be76a4e7fd3a072d573aa4c130e63d) has been merged in which should fix this
