### ISSUE TITLE
TypeError: wysi is undefined

### ISSUE THREAD

**Issue by zeekerg** [jhollingworth/bootstrap-wysihtml5#167]
The script and css are loading correct.
The error is sighting in this line of code: var editor = new wysi.Editor(this.el[0], options);

**Comment by zeekerg** [comment]
The main wysiwyg javascript was missing sorry.

**Comment by alexykot** [comment]
this also shows when you include `bootstrap-wysihtml5.js` before `wysihtml5.min.js`. It has to go after, otherwise it also throws `wysi is undefined` error.
