### ISSUE TITLE
Underline is not a supported text style

### ISSUE THREAD

**Issue by hpshelton** [jhollingworth/bootstrap-wysihtml5#18]
Underline should be implemented as a valid text style in addition to bold and italics.

**Comment by jhollingworth** [comment]
I have implemented the UI on my side but waiting on the latest rc of wysihtml5 which has support for it

**Comment by jhollingworth** [comment]
[Underline functionality has been added](https://github.com/jhollingworth/bootstrap-wysihtml5/commit/0faacfead0f659db20df4efc175aac93a00835e9). Pull the latest version (you will need [wysihtml5 rc3](https://raw.github.com/jhollingworth/bootstrap-wysihtml5/master/lib/js/wysihtml5-0.3.0_rc3.min.js) as well).

Thanks,
James
