### ISSUE TITLE
wysiwyg-color.css not found error

### ISSUE THREAD

**Issue by Enalmada** [jhollingworth/bootstrap-wysihtml5#183]
This script is mentioned in the javascript but not in the overview instructions:
["./lib/css/wysiwyg-color.css"]

This causes browser error...
"NetworkError: 404 Not Found - http://localhost:9000/.../lib/css/wysiwyg-color.css"

I assume the file should either be mentioned in the overview or removed from the js

**Comment by damonjentree** [comment]
Try adding this to your config options:

"stylesheets": false

**Comment by jhrabows** [comment]
This is a valid documentation issue. We need a sentence which explains that 'color' option requires additional css file which needs to be listed in "stylesheets" array.

**Comment by brainbaking** [comment]
"stylesheets": false is NOT valid 
![false](https://f.cloud.github.com/assets/304593/512061/b4991032-be18-11e2-881b-e7a587613110.png)

You'll need "stylesheets": empty array

**Comment by DPSever** [comment]
To expand on @wgroeneveld, you need the following option:

<pre>"stylesheets": [] //CSS stylesheets to load</pre>

This also fixes mime type issues in Internet Explorer.

**Comment by CaptainQuirk** [comment]
The path to the referenced file is wrong. It seems to be relative to the current url, not to the website's root.

**Comment by flyersun** [comment]
I'm having the same issue. I need to change the live path for lib/css/wysiwyg-color.css, not sure how to do this?

**Comment by gplv2** [comment]
Seems to work for me this fix.  There isn't a file like that on my whole disk.  Do we need  it ?

**Comment by sumit-sharma** [comment]
Open bootstrap-wysihtml5.js Search "**stylesheets:**  " on **line no 453**
change path **wysiwyg-color.css** if not available  download from github 
It worked for me

**Comment by AlexandrM** [comment]
In IE (internet explorer) not work color button
1. Select text
2. Click on select color dropdown
   2.1. In Chrome text selection stay on
   2.2. In IE text selection clear
3. On select color 
   3.1. Chrome - color changed
   3.1. IE - color unchanged

I think problem in selection clear.

**Comment by churiart** [comment]
@CaptainQuirk Current wysihtml5 v0.3.0 line [5506](https://github.com/xing/wysihtml5/blob/master/dist/wysihtml5-0.3.0.js#L5506), an slash is missed. You can however add it:
`html += '<link rel="stylesheet" href="/' + stylesheets[i] + '">';`

**Comment by farabf33** [comment]
open bootstrap-wysihtml5.js,[ find stylesheets: [](url) and edit the URL of `wysiwyg-color.css`.

**Comment by nalonsor** [comment]
Try adding this to your config options:

"stylesheets": '../css/wysiwyg-color.css'

try to set the css location, it works for me.
