### ISSUE TITLE
multiple editable sections

### ISSUE THREAD

**Issue by Theadd** [jhollingworth/bootstrap-wysihtml5#19]
Hello, first of all, thank you for sharing your work with us but damn, give us some documentation next time, it took me almost 2 hours to figure out how to retrieve the modified data from the "textarea" and sure it could be done easier than I did.

``` html
<section id="useless" class="editable-section">
    You can use the following commit from hinrik to make tags work properly.
    https://github.com/hinrik/bootstrap-wysihtml5/commit/d9c43dedf7be76a4e7fd3a072d573aa4c130e63d
</section>
<section id="useless" class="editable-section">
    &nbsp;
</section>
```

And here goes the implementation, it sucks but works:

``` javascript
$(function() {

    $('.editable-section').each(function(index) {
        $(this).wrapInner('<div class="editable" />');
        //$(this).children("div.editable").load("load.php", {id: 'something'});
        $(this).append('<a id="edit-section" href="#"><i class="icon-edit"></i> Edit</a>');
    });

    $("a#edit-section").live("click", function(){
        $("#save-section").click();     //save and remove other active editors so we can create a new one
        $(this).before('<textarea id="editable"></textarea>');
        $(this).prev().html($(this).prev().prev().html());
        $(this).prev().prev().hide();
        $(this).prev().show();
        $(this).prev().wysihtml5();
        $(this).parent().append('<a id="save-section" href="#"><i class="icon-share"></i> Save</a>');
        $(this).hide();
    });

    $("a#save-section").live("click", function(){
        $(this).parent().children("div.editable").html($('#editable').val());    //fixed
        $(this).parent().children("div.editable").show();
        var content = $('#editable').val();    //fixed
        $(this).parent().find("iframe.wysihtml5-sandbox").contents().find("html").remove(); //remove iframe html
        $("#editable-wysihtml5-toolbar").remove();
        $(this).parent().find("iframe.wysihtml5-sandbox").prev().remove();
        $(this).parent().find("iframe.wysihtml5-sandbox").remove(); //remove iframe
        $(this).parent().children("#editable").remove();    //remove textarea
        $().remove(wysihtml5);
        $(this).prev().show();      //show edit button
        $(this).remove();   //remove save button

        //finally, update server content
        //$.post("save.php", { id: 'something', html: content } );
    });

});
```

Have a good day.

**Comment by jhollingworth** [comment]
I'm a bit confused. why not just do $('#textarea').val()?

**Comment by Theadd** [comment]
uff, that was stupidly simple but that's not what the above code does.
To reach this `$('#editable').val();` I was doing `$(this).parent().children("div.editable").html();`. But the code above is an implementation of your code to support multiple editable sections like in [this](http://visualdb.es/bootstrap/docs/?id=djs) page. (click edit, edit it and save). Maybe someone is interested in it so I posted it here instead of cleaning up my code, forking, commiting and doing a pull request. (yeah, kind of lazy man)

**Comment by jhollingworth** [comment]
The previous version of wysihtml5 had a bug which meant multiple editors wasn't supported. That's fixed now so this should all be a bit easier :)

I will be adding to the wiki today as well. Thanks for the feedback

**Comment by Bratzilla** [comment]
I just tried to create multiple editable sections using the following method:

```
$('.textarea').wysihtml5();
$('.textarea1').wysihtml5();
```

This did not work, and I get the following message in my console:

Uncaught Error: HIERARCHY_REQUEST_ERR: DOM Exception 3 

This is in the latest version of Chrome.

Multiple instances however work perfectly with regular WYSIHTML5 (did extensive testing).

Is there a special way to create multiples that is not documented? Thanks!

**Comment by rrosiek** [comment]
I'm having the same issues as well when creating multiple text area editors regardless of selections (unique ID's as well).  I'll try to debug and see what I can find, but it does appear to be an issue with the bootstrap skin and not wysihtml5 itself.

**Comment by jhollingworth** [comment]
This should be fixed in the latest code (https://github.com/jhollingworth/bootstrap-wysihtml5/blob/master/src/bootstrap-wysihtml5.js)

**Comment by rrosiek** [comment]
Outstanding.  I had just downloaded the minified version which was newer than mine, didn't notice you just updated the source.  Works like a charm, thanks!
