### ISSUE TITLE
"color": true, but the toolbar has no colour button

### ISSUE THREAD

**Issue by geekyme** [jhollingworth/bootstrap-wysihtml5#191]
i initialized as follows:

```
$('#test').wysihtml5({
"font-styles": true, //Font styling, e.g. h1, h2, etc. Default true
"emphasis": true, //Italics, bold, etc. Default true
"lists": true, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
"html": false, //Button which allows you to edit the generated HTML. Default false
"link": false, //Button to insert a link. Default true
"image": false, //Button to insert an image. Default true,
"color": true //Button to change color of font  
});
```

The colour button does not appear. Why is that?

**Comment by yusuf** [comment]
Make sure you are loading the files located in /src folder

And the path to the wysiwyg-color.css is correct!

**Comment by jhrabows** [comment]
See also https://github.com/jhollingworth/bootstrap-wysihtml5/issues/183

**Comment by yusuf** [comment]
#jhrabows wouldn't it be easier if at the top a variable is set for path-to-app-css so users can easily change the path. As, not in all scenarios, we can have the css path in ./lib/css/wysiwyg-color.css, like when using a MVC framework!

Something like :
var csspath = (window.location.href).slice(0,(window.location.href).indexOf("/",(window.location.host).length+9))+"/lib/css/";

and change :

stylesheets: [csspath+"wysiwyg-color.css"]

BTW, great work!

**Comment by geekyme** [comment]
Got it guys thanks.

**Comment by togoenvogue** [comment]
Hello,
I have an issue with the "color": true property.
After calling : 

$('#test').wysihtml5({
"font-styles": true, //Font styling, e.g. h1, h2, etc. Default true
"emphasis": true, //Italics, bold, etc. Default true
"lists": true, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
"html": false, //Button which allows you to edit the generated HTML. Default false
"link": false, //Button to insert a link. Default true
"image": false, //Button to insert an image. Default true,
"color": true //Button to change color of font  
});

I can see the color button there, but when I select a text and select a color, the text does not change color.

Do you have any idea please ?

Thank you

**Comment by nandodutra** [comment]
@togoenvogue I have the same issue that you had, you did solve this issue?
