### ISSUE TITLE
Required text area stays red

### ISSUE THREAD

**Issue by hinrik** [jhollingworth/bootstrap-wysihtml5#21]
If the wysihtml5 text area is marked required, it will have the required styling (including red text) even after text has been entered in it. This is obviously due to the markup being entirely different (iframe n' all) from what Bootstrap expects. Maybe a workaround is possible?

**Comment by hinrik** [comment]
Sorry, this was actually caused by the HTML5 browser validations I had activated.

**Comment by TinaJ** [comment]
I have the same problem you had. Can you please tell me how you fixed it? Thanks
