### ISSUE TITLE
inserting images

### ISSUE THREAD

**Issue by miclovich** [jhollingworth/bootstrap-wysihtml5#22]
Image upload features? Are there plans to introduce an image uploader for image support I mean.

**Comment by jhollingworth** [comment]
Hi, that's next on the list :)

**Comment by miclovich** [comment]
that's awesome... :)

**Comment by jhollingworth** [comment]
Hi, You can now insert images into the page (see http://jhollingworth.github.com/bootstrap-wysihtml5/). At the moment only insert image url's works (that's whats supported by wysihtml5) - doing proper image uploads will get a little more tricky.

I hope this helps

Thanks,
James

**Comment by miclovich** [comment]
thanks a lot; I understand; this can get tricky and will depend on the backend framework being used; I work with rails, I think I can provide a patch or gem that should work a lot like https://github.com/thoughtbot/paperclip for anyone wanting to persist images in a form of datastore. I'm sure other devs will come up with a solution that could involve their frameworks (wordpress, kohana, etc.). Thanks.

**Comment by jamesosb** [comment]
Miclovich, did you get anywhere near creating something what would allow saving of images through paperclip? I have a similar need now. It would be great to see anything you created?

Thanks!

**Comment by syewell** [comment]
I have a similar need as well, would love to hear what you put together!

Thanks!

**Comment by anu-vaid** [comment]
+1

**Comment by bassjobsen** [comment]
Please see https://github.com/bassjobsen/wysihtml5-image-upload/ to upload and insert images with Bootstrap Wysihtml5. You have to wrote your own handlers (server side) to store your uploads.

**Comment by trantorLiu** [comment]
I just created a new repository for this feature.
I integrated bootstrap-wysihtml5 with [jQuery-File-Upload](https://github.com/blueimp/jQuery-File-Upload).

See https://github.com/trantorLiu/bootstrap-editor.

**Comment by r00takaspin** [comment]
+1

**Comment by trantorLiu** [comment]
I forked this project and created a new branch [**file-upload**](https://github.com/trantorLiu/bootstrap-wysihtml5) for this feature.
I decided to close the [bootstrap-editor](https://github.com/trantorLiu/bootstrap-editor) project and move it to that branch.
