### ISSUE TITLE
example of link creation code?

### ISSUE THREAD

**Issue by mpelzsherman** [jhollingworth/bootstrap-wysihtml5#23]
Can anyone provide an example of a "create link" button that functions similarly to the "insert link" menu item in this example:? 

http://tifftiff.de/wysihtml5/examples/advanced.html

Thanks!

**Comment by hinrik** [comment]
Is that really needed? As of 4d553cf23d, all you need to do is paste (or type) a url into the textarea and it just works.

**Comment by mpelzsherman** [comment]
Yes, but I want to be able to convert the selected text into a hyperlink.

**Comment by hinrik** [comment]
Ah, I see. Yeah, that would need to be implemented.

**Comment by jhollingworth** [comment]
It's on the list of things to do :)

**Comment by jhollingworth** [comment]
There is now an insert link button which is shown by default. wysihtml5 currently doesn't allow you to specify the link text, I will see if I can add that functionality
