### ISSUE TITLE
data-wysihtml5-command-value the only not working part

### ISSUE THREAD

**Issue by Jaspur** [jhollingworth/bootstrap-wysihtml5#256]
The functions that make use of the `data-wysihtml5-command-value` are not working in Safari/Chrome for me. So the colors and font-styles. 
The other parts that are triggered with `data-wysihtml5-command` for example do work.
Is there something I'm missing why they're not working? Because the demo online works.

**Comment by renege** [comment]
Same problem here! #bug

**Comment by renege** [comment]
@jhollingworth working with bootstrap v2.3.0 and jquery 1.9.1!
