### ISSUE TITLE
Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by panosru** [jhollingworth/bootstrap-wysihtml5#28]
Hi, when I try to instantiate the editor I'm getting the error I type on the title.

![wysihtml5-error](http://dl.dropbox.com/u/16165490/Screenshots/wysihtml5-error.png)

Thanks :)

**Comment by jhollingworth** [comment]
Hmm, odd. could you provide me with some more info? browser, os, etc.

Thanks!

**Comment by panosru** [comment]
@jhollingworth 

hi, the above screenshot is from Google Chrome, but I have the same error on Safari and Firefox

I'm on OSX :)

**Comment by jhollingworth** [comment]
hmm annoying - I've got it open in chrome on osx right now and everything is fine. 

it might be a script ordering or something. any chance you could send me more of the html?

**Comment by panosru** [comment]
@jhollingworth well to be honest I put tinymce for not but I'll try to find some time and add it again so you could test it.. :)

**Comment by jhollingworth** [comment]
ah ok, no problem :) my fault for not responding sooner! 

I will close for now, if you find the time to get me some more info I will re-open.

Thanks!

**Comment by XayOn** [comment]
I probably can explain this, that error ocurs if the id of the element is not unique, or if you pass it an object without any id.

**Comment by panosru** [comment]
@XayOn hmm I guess you could be right on that! I just tried it and made sure the id is unique and it works! :) (I just have an anoying backdrop modal on load but I'll figure it out :P )

**Comment by bernatbombi** [comment]
Had the same problem, and solved it setting an Id for every textarea... crappy js :D

**Comment by rashidshafique** [comment]
for anyone still getting it, make sure the ids you pass when initializing the editor, that they are unique and exist on the page, this includes the toolbar as well and off course the textarea.
