### ISSUE TITLE
Viewing HTML Source

### ISSUE THREAD

**Issue by azolotov** [jhollingworth/bootstrap-wysihtml5#29]
It would be great to be able to toggle back and forth between the wysiwig and source (html) views.

**Comment by barmstrong** [comment]
Agreed - this would be nice.

**Comment by jhollingworth** [comment]
I have added support to edit the html. It's not on by default, to use you need to do:

``` javascript
$('#textarea').wysihtml5({
    "html": true
});
```

Let me know if there are any issues

**Comment by michaeljcoyne** [comment]
why?
