### ISSUE TITLE
Auto Close Styles Dropdown

### ISSUE THREAD

**Issue by EricR** [jhollingworth/bootstrap-wysihtml5#3]
When the styles dropdown is open, auto-closing doesn't work if the user clicks in the textarea. Only the area outside of the textarea properly closes the dropdown. This is an issue because the user can focus on the textarea while the dropdown is still open, which can be annoying.

**Comment by jhollingworth** [comment]
Good point, I will look into it ASAP

**Comment by brandonb927** [comment]
I came here actually to open the same issue. Good work though!

**Comment by buzzedword** [comment]
Looks like there needs to be a focus event bubbled up to the iframe wysihtml5 creates so any dropdowns currently open get the "open" class removed. Sussing through it now to submit a pull.

**Comment by buzzedword** [comment]
Just updated the pull request on #11. We'll see!

**Comment by jhollingworth** [comment]
Merged in @buzzedword's fix :)

**Comment by brian-spinos** [comment]
so how can I make the drop-down button work?

thanks in advance!
