### ISSUE TITLE
Should the indent/outdent button positions be reversed?

### ISSUE THREAD

**Issue by barmstrong** [jhollingworth/bootstrap-wysihtml5#31]
From a UI perspective I found it confusing that indent was on the left and outdent was on the right.

Indent has a right arrow and visually looks like it will push something to the right, so I expected it to be on the right.

This is how Microsoft Word is setup also, which is many people's reference point: http://cl.ly/2o2F1e1j1a1j1h0d051x

In general looks like it's coming along nicely though.  Awesome work!

**Comment by silasb** [comment]
I think it should. When I saw the indent buttons, and not looking very closely, I ended up clicking on the right de-indent button thinking it was the indent button.

**Comment by jhollingworth** [comment]
Agreed. Updated.
