### ISSUE TITLE
Has anyone gotten capybara testing working with this?

### ISSUE THREAD

**Issue by barmstrong** [jhollingworth/bootstrap-wysihtml5#32]
Not really an issue with bootstrap-wysihtml5 directly, but figured I'd ask.

I'm having trouble getting capybara to fill out the textarea, or the body inside the iframe for testing.

Was wondering if anyone found a way to do this.  Thanks!

**Comment by jhollingworth** [comment]
Sorry, haven't tried it as of yet. If I get a chance over the next few days I will have a play

Thanks!

**Comment by mattbeedle** [comment]
Having the same problems. Did anyone figure this out yet?

**Comment by kbaum** [comment]
Also having a problem with this.  Anyone have any luck?

**Comment by edslocomb** [comment]
We haven't been able to get this working yet either, but it seems it might be less a problem with bootstrap-wysihtml5 than with combining the underlying wysihtml5 library with capybara.  It looks like capybara may need an id to address a document in an iframe (via <a href="http://rubydoc.info/github/jnicklas/capybara/master/Capybara/Session#within_frame-instance_method">within_frame</a>), and wysihtml5 does not set an id on the iframe it creates.

**Comment by kbaum** [comment]
Interesting.. even using pure jquery i wasn't able to get hold of the wysihtml5 object within the iframe.  It seemed like the data method did not work within another iframe.

```
$('textarea#shared_space_message_html', frames['sb-content'].document).data("wysihtml5")
undefined
```

The same command returns the object when not accessed through the iframe.

**Comment by edslocomb** [comment]
Ah, it looks like you're trying to do something different, instantiating the editor within an iframe you've set up yourself.

I'm referring to the simple case, where the only iframe in the application is the one wysihtml5 itself creates to house its contenteditable document; capybara doesn't seem to be able to get ahold of anything within that iframe.

**Comment by dgilperez** [comment]
+1 . No luck here after a bunch of time of trying ...

**Comment by kbaum** [comment]
I was able to get it to work using execute_script:

```
page.execute_script %Q{ $('#textarea').data("wysihtml5").editor.setValue('#{text}') }
```

Where textarea is the id of the initial textarea.  I am using capybara-webkit.

**Comment by dgilperez** [comment]
Thanks @kbaum !!! I also manage to get it working.

**Comment by juliobetta** [comment]
Thanks @kbaum !!! |o/

**Comment by PedroSena** [comment]
Thanks @kbaum 

I used the same idea for the Redactor editor, the final code is: $('#article-content').setCode('#{attributes[:content]}')
