### ISSUE TITLE
jQuery 10.2 Error

### ISSUE THREAD

**Issue by Page-Carbajal** [jhollingworth/bootstrap-wysihtml5#324]
Uncaught TypeError: 
Cannot read property 'Editor' of undefined bootstrap-wysihtml5.js:156
Wysihtml5.createEditor bootstrap-wysihtml5.js:156
Wysihtml5 bootstrap-wysihtml5.js:131
(anonymous function) bootstrap-wysihtml5.js:356
x.extend.each jquery-1.10.2.js:657
x.fn.x.each jquery-1.10.2.js:266
methods.bypassDefaults bootstrap-wysihtml5.js:354
methods.shallowExtend bootstrap-wysihtml5.js:362
methods.init bootstrap-wysihtml5.js:371
$.fn.wysihtml5 bootstrap-wysihtml5.js:379
(anonymous function)

**Comment by Page-Carbajal** [comment]
Corrupt file. Downloaded it again and worked.

**Comment by pavankumar542** [comment]
http://xing.github.io/wysihtml5/ while iam trying to implement it in aspx page and opening the design part is showing error that design canoot be opened
example of errors are
Error   45  Validation (XHTML 1.0 Transitional): Attribute 'data-wysihtml5-dialog-action' is not a valid attribute of element 'a'.  D:\pavanWork\html editor\xing-wysihtml5-0.3.0-0-g9c73556\xing-wysihtml5-fb0cfe4\website\Editor.aspx 60  63  D:...\website\
