### ISSUE TITLE
Update for Bootstrap 3

### ISSUE THREAD

**Issue by ftbastler** [jhollingworth/bootstrap-wysihtml5#325]
Please update this for Bootstrap v3

**Comment by benoitbssr** [comment]
Even for Bootstrap 3.1 !

**Comment by tomkrus** [comment]
This repo is dead. This fork is ok https://github.com/Waxolunist/bootstrap3-wysihtml5-bower

**Comment by Waxolunist** [comment]
Since v0.2.8 also with Bootstrap 3.1 support.

**Comment by manikantareddygk** [comment]
I am not able to insert data into textarea using in ajax calls jquery ,
$(document).ready(function(){
$.ajax({
                    url: "/wikipost",
                    type: "POST",
                    data: JSON.stringify(data),
                    contentType: 'application/json',
                    datatype: "json",
                    success: function (datas) {
                        console.log('success');
                        var res = JSON.stringify(datas);
                        console.log(res);
                        $.each(datas, function (index, element) {
                            $('#textarea').val(element.extract) 
                        });
});
I also used .val(), .html(), .append() neither  of these worked 
please help me out, am I missing something ? ...........

**Comment by Waxolunist** [comment]
Answered in my repo - https://github.com/Waxolunist/bootstrap3-wysihtml5-bower/issues/37
