### ISSUE TITLE
Resize images

### ISSUE THREAD

**Issue by cxanthos** [jhollingworth/bootstrap-wysihtml5#33]
Using the editor, i'm using wysihtml5.commands.exec('insertHtml', "..."); to insert images, which works fine.
I'm trying to add a resize functionality for the images, have set allowObjectResizing option of the editor to "true", but nothing happens.
Is this option really working?

**Comment by jhollingworth** [comment]
I think this is more of a wysihtml5 question, it's probably worth asking on their issues list https://github.com/xing/wysihtml5/issues

Thanks!

**Comment by elfassy** [comment]
https://github.com/xing/wysihtml5/issues/69
