### ISSUE TITLE
Improved Documentaiton

### ISSUE THREAD

**Issue by blanchardjeremy** [jhollingworth/bootstrap-wysihtml5#35]
It's really unclear from the readme how to get started.

A few questions that I think should be answered:
- For the two bootstrap-wysihtml5 files, wysihtml5, and bootstrap: where do they all need to be located relative to one another ot have access to each other (this is the biggest one)
- Which of the possible files do I need to include at the top of a page to get it work
- Do I need to download ALL of files for each of the libraries or can I just get the "end use" files?

If there were answered in the "getting started" code block in the readme, that would be really helpful.

**Comment by hinrik** [comment]
It might also be worth mentioning [bootstrap-wysihtml5-rails](https://github.com/Nerian/bootstrap-wysihtml5-rails) for Rails users.

**Comment by jhollingworth** [comment]
Plan for today: improve documentation :)

**Comment by jhollingworth** [comment]
Hi, I've improved the readme with more info (https://github.com/jhollingworth/bootstrap-wysihtml5), added a download which has all the required files (https://github.com/jhollingworth/bootstrap-wysihtml5/downloads) and also mentioned the bootstrap-wysihtml5-rails gem on the readme file for any rails devs. 

I hope that helps! 

Thanks,
James

**Comment by blanchardjeremy** [comment]
Thanks for improving the readme!

I think there needs to be a bit more for the documentation to help someone get from nothing to a working version of the code: It needs to mention the exact lines you need to have in your code for bootstrap-wysihtml5 to work. The part that your readme is still missing are the javascript and CSS imports that are required to get this working.

This includes:

<link rel="stylesheet" type="text/css" href="src/bootstrap-wysihtml5.css"></link>
<link rel="stylesheet" type="text/css" href="lib/css/bootstrap.min.css"></link>

<script src="lib/js/wysihtml5-0.3.0_rc2.js"></script>

<script src="lib/js/jquery-1.7.1.min.js"></script>

<script src="lib/js/bootstrap.min.js"></script>

<script src="src/bootstrap-wysihtml5.js"></script>


And the readme should include instructions on where to download each of those files at, and where to place them relative to each other in your site.

I spent a bunch of time reading your docs/examples and the normal wysihtml5 docs/examples to figure out which files in the big repos were necessary for me and how I placed them relative to one another in my site directory to get them all to be included.

Thanks!

**Comment by jhollingworth** [comment]
Updated readme file with exact files that need to be referenced (https://github.com/jhollingworth/bootstrap-wysihtml5).

The zip file in the downloads section (https://github.com/jhollingworth/bootstrap-wysihtml5/downloads) contains everything you need to get started with it.

Thanks for the feedback :)

**Comment by blanchardjeremy** [comment]
Perfect! You rock. Thanks.

Last thing I would say is to reference the download from the readme so it's as simple as:
- look at read me
- click download link
- drop files into project
- copy past code into project
- done!
