### ISSUE TITLE
spellchecker

### ISSUE THREAD

**Issue by caBBAlainB** [jhollingworth/bootstrap-wysihtml5#360]
Hi,
Any chance to see a spellchecker included ?

Regards,
Alain

**Comment by JeremyCade** [comment]
Hi @caBBAlainB, 

What is your use case? Most modern browsers include this feature (spell checking on input fields and text-areas) by default. 

![screen shot 2015-06-12 at 10 44 32 pm](https://cloud.githubusercontent.com/assets/492782/8130323/b53d1f6a-1154-11e5-9cce-02991076eb26.png)
**Figure:** Firefox 38.0.5 Spell Check in WYSIYG field.

**Comment by caBBAlainB** [comment]
well, maybe you are right...
