### ISSUE TITLE
insert link bug

### ISSUE THREAD

**Issue by BondWong** [jhollingworth/bootstrap-wysihtml5#361]
Goes wrong every time I insert a link.
Hers is the pix
![screen shot 2015-06-24 at 20 30 02](https://cloud.githubusercontent.com/assets/6009781/8329882/dfdbcfdc-1aaf-11e5-9d5b-4aa4d844eace.png)
![screen shot 2015-06-24 at 20 30 07](https://cloud.githubusercontent.com/assets/6009781/8329883/dfe62b30-1aaf-11e5-8ead-00c17bf49594.png)

is it a bug or something, can anyone tell me where the codes are so that I can check it out.

**Comment by ryanwanger** [comment]
I think that works as expected. If you just click the insert link button, and then type a url into, it will put the url into the text area, and hyperlink it.

If you type some other text into the text area first, highlight it, then click insert link, it will link the text you highlighted to whatever url you put into the insert link dialog.

**Comment by ryanwanger** [comment]
However, for me, the "open link in new window" option does not work at all.

**Comment by BondWong** [comment]
recent version does not have this issue. it is a bug of much order version.
