### ISSUE TITLE
Make it easier to use wysihtml5 events

### ISSUE THREAD

**Issue by tacovoyager** [jhollingworth/bootstrap-wysihtml5#38]
It'd be really more intuitive and easier to be able to attach events to the wysihtml5 editor if we could pass callbacks in via the options collection. Events: https://github.com/xing/wysihtml5/wiki/Events

Current syntax:

``` javascript
var textarea = $('#my-textaera').wysihtml5()
textarea.data('wysihtml5').editor.on('change', someCallback);
```

I think this would be nicer:

``` javascript
$('#my-textaera').wysihtml5({
  events: {
    'change': someCallback
  }
})
```

**Comment by jhollingworth** [comment]
Agreed and added in :)

You can add events like so:

``` javascript
$('#textarea').wysihtml5({
    events: {
        "load": function() { 
            console.log('loaded!');
        }
    }
});
```

Thanks!
