### ISSUE TITLE
cannot read property 'Editor' of undefined.

### ISSUE THREAD

**Issue by ric03uec** [jhollingworth/bootstrap-wysihtml5#41]
using Chrome on ubuntu 11.10
The error is thrown from line number 145 of file bootstrap-wysihtml5.js when initializing a text area with the following line.

$('#some-text-area').wysihtml5();

**Comment by ric03uec** [comment]
Moved the script includes to footer. Solved the problem.

**Comment by volmer** [comment]
I'm not sure if this is a good solution for this issue, once Rails by default inserts all scripts on the page header.

**Comment by smizell** [comment]
Just an FYI: I had this happen to me when I switched versions without restarting the webrick. After restarting webrick, the error went away.

**Comment by xamiam** [comment]
Moving the script includes to the footer didn't solve it for me. I made sure the textarea has a valid ID and the jquery-selector is fine. Any Ideas? Thanks a lot.

**Comment by Darksoulsong** [comment]
I got the very same problem. The scripts are in the footer and are loaded following this sequence:
- jquery (1.8.3)
- bootstrap.min.js
- main js script

**Comment by andineck** [comment]
I get the same error as well, but only ocasionally, sometime it loads fine, seems to be a timing problem with loading of the script.

**Comment by andineck** [comment]
Firs I applied the hack #274 and it worked. Later I found out that the problem was my script loader. It loaded the scripts in parallel. So the order was not defined. When I ensured that the loader would only load the next script once the previous was loaded, it worked fine. `wysihtml5-xxx.js` must have been loaded before `bootstrap-wysihtml5-xxx.js` starts loading.

**Comment by asakapab0i** [comment]
i have this problem also any fix to this?

**Comment by jaminto** [comment]
You've got to include the scripts in the right order as detailed in the readme:

```
<script src="js/wysihtml5-0.3.0.js"></script>
<script src="js/jquery-1.7.2.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/bootstrap-wysihtml5.js"></script>
```

i got this error when `wysihtml5-0.3.0.js` was not in order before `bootstrap-wysihtml5.js` like @andi-neck said, but i didn't need to do his hack first.
it doesn't matter if they're in the `<head>` or bottom of the `<body>` tag...
