### ISSUE TITLE
Flushing textarea

### ISSUE THREAD

**Issue by monkeymademe** [jhollingworth/bootstrap-wysihtml5#44]
Hey guys,

Might be totally stupid here but I have a textarea in modal and every time I open it I want to flush the form (aka remove all text from the textareas).

I used this     

```
 var flushform = "";
 $('input[name="addtstepshortdesc"]').val(flushform); 
 $('textarea[name="addtsteplongdesc"]').val(flushform);
 $('textarea[name="addtstepexpected"]').val(flushform);
```

But it does not seem to work... any ideas.

**Comment by maciejwalkowiak** [comment]
``` javascript
$('.wysihtml5-sandbox').contents().find('body').html('');
```

Worked on example: http://jhollingworth.github.com/bootstrap-wysihtml5/

**Comment by monkeymademe** [comment]
Thanks Maciej
