### ISSUE TITLE
Listening for key presses on the RTE

### ISSUE THREAD

**Issue by kishorenc** [jhollingworth/bootstrap-wysihtml5#49]
How do I listen for specific key presses like Ctrl+K etc. on the editor? I was using the jQuery hotkeys plugin on the plain textarea, but how do I do the same for the rich text editor?

**Comment by kishorenc** [comment]
Realized it's more of wysihtml5 related question. Anyway - for future explorers, using the jQuery hotkeys plugin we can do:

```
 $('.wysihtml5-sandbox').ready(function() {
        $('.wysihtml5-sandbox').attr('id', 'editor_iframe');
        var frame = document.getElementById("editor_iframe");
        var frameWin=(frame.contentWindow || frame.contentDocument);

        $(frameWin.document).bind('keydown', 'ctrl+s', doSomething);
});
```

**Comment by dizzyn** [comment]
Hello, please, is this the only way how to bind events on the editor?
