### ISSUE TITLE
Support for outlining

### ISSUE THREAD

**Issue by pixelcort** [jhollingworth/bootstrap-wysihtml5#5]
The ability to nest lists into outlines would be pretty cool.

**Comment by buzzedword** [comment]
Can you give an example for this? Seems interesting, I might want to take a stab at it.

**Comment by pixelcort** [comment]
Take a look at Google Docs. Pressing the tab key indents.

On Tuesday, March 20, 2012, Daniel Garcia <
reply@reply.github.com>
wrote:

> Can you give an example for this? Seems interesting, I might want to take
> a stab at it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/jhollingworth/bootstrap-wysihtml5/issues/5#issuecomment-4603592

## 

Cortland Klein me@pixelcort.com +1 408 506 9791
http://pixelcort.com/
400A Ortega Ave. Unit 319
Mountain View, CA 94040

**Comment by buzzedword** [comment]
Oh, you're talking nested lists. Like:
-  this
  - and this

as compared to
-   this
-   and this

**Comment by buzzedword** [comment]
Looks like xing/wysihtml5@3c03dc6e222b9c5dbe2be9f7426aa523c532683c doesn't support that. Not much can be done until that's patched up. I'll dig around on their side.

**Comment by allochi** [comment]
Hi,

try this, replace the list section in the file bootstrap-wysihtml5.js with the following:

``` javascript
"lists": "<li>" +
    "<div class='btn-group'>" +
    "<a class='btn' data-wysihtml5-command='insertUnorderedList'><i class='icon-list'></i></a>" +
    "<a class='btn' data-wysihtml5-command='insertOrderedList'><i class='icon-th-list'></i></a>" +
    "<a class='btn' data-wysihtml5-command='Indent'><i class='icon-indent-left'></i></a>" + 
    "<a class='btn' data-wysihtml5-command='Outdent'><i class='icon-indent-right'></i></a>" + 
    "</div>" +
    "</li>",
```

Worked for me.

**Comment by buzzedword** [comment]
Huh! That's interesting. I'll send a pull in with the changes after testing it out. Nice find, @allochi!

**Comment by jhollingworth** [comment]
Merged in [@buzzedword's pull request](https://github.com/jhollingworth/bootstrap-wysihtml5/pull/24). Closing :)
