### ISSUE TITLE
inserting text using js

### ISSUE THREAD

**Issue by ric03uec** [jhollingworth/bootstrap-wysihtml5#52]
this is more of a query than an issue. I want to insert  a piece of text/html into the editor after i fetch it from the server.  How can i set that value in the already existing wysihtml5 editor instance.
i tried doing following

var editor = $('#sometextarea').wysihtml5().data('wysihtml5').editor;
editor.setValue('some value i want to set');
or
$('#sometextarea').val('some value');
or
$('#sometextarea').html('some html');
none of these seem to work.
can help me out on this.
thanks

**Comment by thomasjonas** [comment]
I have this same issue... 

$('#some-textarea').wysihtml5().data("wysihtml5").editor.setValue('test', true);

This does update the underlying textarea value, but not the editor itself... I would love to see an example of how you could set the value of the editor when it's already been initialized.

**Comment by ric03uec** [comment]
@thomasjonas : go to the following link for a complete example of updating the text as well as the editor.

https://github.com/ric03uec/nodeblox/blob/master/public/js/admin/admin.js

In summary
1. keep the 'editor' as the global accessible variable.
2. initialize the 'editor' with the appropriate configuration during js initialization
3. use the following to update the text and the editor

```
    var editorInstance = editor.data('wysihtml5').editor;
    editorInstance.setValue('some text to be inserted into editor', true);
```

Let me know if this works for you.

**Comment by stesteau** [comment]
Well it kind of work, the editorInstance instance value gets updated, but the wysihtml5 does not, no text is added.

i.e.

``` javascript
var wysihtml5Editor = $('.company-about-editor').wysihtml5().data("wysihtml5").editor;
wysihtml5Editor.setValue("<p>foobar</p>", true);
console.log(wysihtml5Editor.getValue());
```

So basically, this makes the plugin pretty useless, you cannot set the text...

**Comment by sachininmindfire** [comment]
This code worked for me :
$(this.el).find('.textareaContent').wysihtml5();
editor.setValue("abc");

Here "editor" is kinda global var set after wysihtml5 initialization. We can use that.

**Comment by stationkeeping** [comment]
This doesn't work at all. How can such a crucial feature be non-functional and undocumented?

**Comment by BobMabena** [comment]
I'm using the following to copy from one editor to another and it works fine:

$('#mobileArticleBody').data("wysihtml5").editor.setValue($('#webArticleBody').val());

**Comment by kojunghee** [comment]
test1

**Comment by cbielich** [comment]
> This code worked for me :
$(this.el).find('.textareaContent').wysihtml5();
editor.setValue("abc");
Here "editor" is kinda global var set after wysihtml5 initialization. We can use that.

This worked for me, thanks
