### ISSUE TITLE
Textarea requires ID

### ISSUE THREAD

**Issue by izstas** [jhollingworth/bootstrap-wysihtml5#53]
I want to use the editor with dynamically created textarea, but when I try to I get an error:
`TypeError: Cannot read property 'parentNode' of undefined`
It can be reproduced using the following code:

``` javascript
var textarea = $('<textarea></textarea>');
textarea.appendTo(document.body);
textarea.wysihtml5();
```

I'd like to see this fixed. Thanks!

**Comment by jhollingworth** [comment]
Hi, wysihtlm5 requires the textarea to have an id. 

this modification should work:

``` javascript
var textarea = $("<textarea id=\"" + new Date().getTime() + "\"></textarea>");
```

Hope this helps!

Thanks,
James
