### ISSUE TITLE
Allow support for elements not yet inserted into dom

### ISSUE THREAD

**Issue by fellars** [jhollingworth/bootstrap-wysihtml5#54]
Simple change to allow for creation of elements that have not yet been added into the dom by changing lines 145,146:
var editor = new wysi.Editor(this.el.get(0), {
                toolbar: this.toolbar.get(0),
                parserRules: parserRules
            });

previously was:
var editor = new wysi.Editor(this.el.attr('id'), {
                toolbar: this.toolbar.attr('id'),
                parserRules: parserRules
            });

this is also better performance as it does not require lookup of element by id by instead just passing in the node directly.

**Comment by pkmishra** [comment]
@fellars  You really saved me. I was wondering about the error then after so much effort I landed on this issue. Thank you so much.

**Comment by fellars** [comment]
@pkmishra glad it helped.  Now hopefully it gets added to master  :)

**Comment by pkmishra** [comment]
Submitted a pull request. https://github.com/jhollingworth/bootstrap-wysihtml5/pull/66

**Comment by jhollingworth** [comment]
Fix should be in there now. Thanks
