### ISSUE TITLE
Can not use classes when initializing

### ISSUE THREAD

**Issue by BoringCode** [jhollingworth/bootstrap-wysihtml5#57]
I have found that it is impossible to use a class name, or even an element name to initialize the plugin. You can only use an ID. 

This definitely needs to be fixed.

**Comment by jhollingworth** [comment]
That's been fixed now. You can use any jQuery selector you want. 

Sorry for the delay in getting back to you on this one

Thanks,
James

**Comment by BoringCode** [comment]
That's great, thanks for the fix.
