### ISSUE TITLE
Set tabindex to -1 for toolbar buttons

### ISSUE THREAD

**Issue by cblock** [jhollingworth/bootstrap-wysihtml5#94]
Hi and thanks for the very nice integration of wysihtml5 and bootstrap.

I just noticed that the default toolbar buttons appear in the regular tab order when navigating a wysihtml5 enriched form. I suggest setting tabindex="-1" for all toolbar buttons so that they are skipped from tab order instead.

Thanks,
Carsten

**Comment by heliostatic** [comment]
+1

**Comment by rahilsondhi** [comment]
:+1:

**Comment by rahilsondhi** [comment]
Can't figure out how to add it to this project, but it was easy to add it to https://github.com/Nerian/bootstrap-wysihtml5-rails/pull/35

**Comment by Nerian** [comment]
Hi Rahil,

Thanks for your contribution. I will update the gem as soon as these changes are merged in this repository.

The file you would need to change in this repository would be:
https://github.com/jhollingworth/bootstrap-wysihtml5/blob/master/src/bootstrap-wysihtml5.js

**Comment by heidiv** [comment]
This disables access to the toolbar for all keyboard/assistive technology users! I would suggest reverting this and instead add a "skip toolbar" link before the toolbar (that is visually hidden but appears when active) that would move the cursor directly to the text area.

**Comment by klown** [comment]
An alternative is to follow the ARIA Authoring Practices.  It suggests to use TAB to navigate to and from the toolbar, and arrow keys to navigate within the toolbar.  See the "Keyboard Interaction" section of the toolbar pattern:
http://www.w3.org/TR/wai-aria-practices-1.1/#toolbar

**Comment by heidiv** [comment]
+1 for klown's advice
