### ISSUE TITLE
Clears href of links if not http

### ISSUE THREAD

**Issue by ScotterC** [jhollingworth/bootstrap-wysihtml5#98]
clears mailto in href both on link use or on load if the href was inputted manually.

**Comment by edslocomb** [comment]
Support for mailto: URLs was added to the upstream wysihtml5 library after the 0.3.0 release.  There hasn't been another versioned release yet, but you could try compiling the edge version and using that instead of wysihtml5-0.3.0.js :

https://github.com/xing/wysihtml5

**Comment by ScotterC** [comment]
I'll give it a try. Thanks.
